# Generated by Django 5.1.1 on 2025-03-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="category",
            field=models.CharField(
                choices=[
                    ("PU", "Pengetahuan Umum"),
                    ("ED", "Edukasi"),
                    ("HI", "Hiburan"),
                    ("BA", "Bahasa"),
                    ("KE", "Kesehatan"),
                    ("OL", "Olahraga"),
                    ("BU", "Budaya"),
                    ("TE", "Teknologi"),
                ],
                default="PU",
                max_length=2,
            ),
        ),
    ]
