# Generated by Django 5.1.6 on 2025-03-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quiz_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="author",
        ),
    ]
